[project]
name = "backhand"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.56",
    "fastapi>=0.133.0",
    "mangum>=0.21.0",
    "openai>=2.24.0",
    "pypdf>=6.7.3",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.22",
    "uvicorn>=0.41.0",
]
